### ISSUE TITLE
Stop preload action

### ISSUE THREAD

**Issue by Johann-S** [flesler/jquery.preload#3]
Hi,

I would like to know how can I stop a preload action ?

**Comment by flesler** [comment]
Based on [this answer](http://stackoverflow.com/a/6036821), there is no standard way to abort a loading (HTML) image.
It mentions that if the `src` is set to empty string it will abort on some browsers.

I suggest you first try doing that, you get the HTML image element on callbacks as `data.image`. If it works please report and it might get added here if it works on (at least) several browsers

**Comment by Johann-S** [comment]
For me it doesn't work and I can't do what I want.
Why did you choose to preload images using `<img>` and not an XHR in JQuery ?

Something like this : 

``` javascript
        $.ajax({
            url: 'http://www.exemple.com/image.jpg',
            beforeSend: function (xhr) {
                // save this XHR request
            }
        });
```

**Comment by flesler** [comment]
Cross domain support

**Comment by Johann-S** [comment]
Ok thank you, finally I generate a ID for each instance of $.preload which allow me to prevent action when it's another preloading
