### ISSUE TITLE
Error with jquery 1.8 or higher

### ISSUE THREAD

**Issue by chrlsmgt** [flesler/jquery.preload#5]
Hi,

I found that the lib throw a "Uncaught TypeError: e.indexOf is not a function" if you use the lib with the latest jQuery version.
jQuery event alias .load is deprecated since jQuery 1.8.

You can resolve this problem by replacing the .load(handler) in jquery.preload.js line 82 by .on('load', handler).
Tested with jQuery 3.3.1.

Thanks for this lib.

**Comment by flesler** [comment]
Thank you, fixed
